CREATE TABLE outages (
    id INTEGER PRIMARY KEY,
    region TEXT NOT NULL,
    delay_code TEXT NOT NULL
);

INSERT INTO outages (id, region, delay_code) VALUES (1, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (2, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (3, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (4, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (5, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (6, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (7, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (8, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (9, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (10, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (11, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (12, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (13, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (14, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (15, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (16, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (17, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (18, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (19, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (20, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (21, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (22, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (23, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (24, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (25, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (26, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (27, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (28, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (29, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (30, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (31, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (32, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (33, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (34, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (35, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (36, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (37, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (38, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (39, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (40, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (41, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (42, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (43, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (44, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (45, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (46, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (47, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (48, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (49, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (50, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (51, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (52, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (53, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (54, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (55, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (56, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (57, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (58, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (59, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (60, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (61, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (62, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (63, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (64, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (65, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (66, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (67, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (68, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (69, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (70, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (71, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (72, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (73, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (74, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (75, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (76, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (77, 'north', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (78, 'south', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (79, 'east', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (80, 'west', 'No Delay');
INSERT INTO outages (id, region, delay_code) VALUES (81, 'north', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (82, 'south', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (83, 'east', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (84, 'west', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (85, 'north', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (86, 'south', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (87, 'east', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (88, 'west', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (89, 'north', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (90, 'south', 'Backhaul');
INSERT INTO outages (id, region, delay_code) VALUES (91, 'north', 'RF');
INSERT INTO outages (id, region, delay_code) VALUES (92, 'south', 'RF');
INSERT INTO outages (id, region, delay_code) VALUES (93, 'east', 'RF');
INSERT INTO outages (id, region, delay_code) VALUES (94, 'west', 'RF');
INSERT INTO outages (id, region, delay_code) VALUES (95, 'north', 'RF');
INSERT INTO outages (id, region, delay_code) VALUES (96, 'north', 'Power');
INSERT INTO outages (id, region, delay_code) VALUES (97, 'south', 'Power');
INSERT INTO outages (id, region, delay_code) VALUES (98, 'east', 'Power');
INSERT INTO outages (id, region, delay_code) VALUES (99, 'west', 'Power');
INSERT INTO outages (id, region, delay_code) VALUES (100, 'north', 'Power');
